spring.application.name=expenseReimbursementPortal

spring.datasource.url=jdbc:postgresql://localhost:5432/expense_reimbursement_portal
spring.datasource.username=anuj
spring.datasource.password=anuj
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

jwt.secret.key=4y5iuheufhoiajefhohjihefoih

debug=true

# Security
#spring.security.user.name=anuj
#spring.security.user.password=anuj123